language: cpp 

sudo: required 

git: 
 depth: 3

matrix:
  include:
    # A. Linux
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        # 1. Only examples and associated tests
        - CMAKE_EXAMPLE='ON' CMAKE_TEST='OFF' CMAKE_UTILITIES='OFF' CMAKE_PYTHON='OFF' MAKE_TARGET='test'
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        # 2. Only unitary tests
        - CMAKE_EXAMPLE='OFF' CMAKE_TEST='ON' CMAKE_UTILITIES='OFF' CMAKE_PYTHON='OFF' MAKE_TARGET='test'
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        # 3. Only utilities and associated tests
        - CMAKE_EXAMPLE='OFF' CMAKE_TEST='OFF' CMAKE_UTILITIES='ON' CMAKE_PYTHON='OFF' MAKE_TARGET='test'
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        # 4. Only doxygen documentation
        - CMAKE_EXAMPLE='OFF' CMAKE_TEST='OFF' CMAKE_UTILITIES='OFF' CMAKE_PYTHON='OFF' MAKE_TARGET='doxygen'
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        # 5. Only Python, associated tests and sphinx documentation
        - CMAKE_EXAMPLE='OFF' CMAKE_TEST='OFF' CMAKE_UTILITIES='OFF' CMAKE_PYTHON='ON' MAKE_TARGET='test sphinx'
    # A. Mac OSX
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        # 1. Only examples and associated tests
        - CMAKE_EXAMPLE='ON' CMAKE_TEST='OFF' CMAKE_UTILITIES='OFF' CMAKE_PYTHON='OFF' MAKE_TARGET='test'
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        # 2. Only unitary tests
        - CMAKE_EXAMPLE='OFF' CMAKE_TEST='ON' CMAKE_UTILITIES='OFF' CMAKE_PYTHON='OFF' MAKE_TARGET='test'
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        # 3. Only utilities and associated tests
        - CMAKE_EXAMPLE='OFF' CMAKE_TEST='OFF' CMAKE_UTILITIES='ON' CMAKE_PYTHON='OFF' MAKE_TARGET='test'
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        # 4. Only doxygen documentation
        - CMAKE_EXAMPLE='OFF' CMAKE_TEST='OFF' CMAKE_UTILITIES='OFF' CMAKE_PYTHON='OFF' MAKE_TARGET='doxygen'
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        # 5. Only Python, associated tests and sphinx documentation
        - CMAKE_EXAMPLE='OFF' CMAKE_TEST='OFF' CMAKE_UTILITIES='OFF' CMAKE_PYTHON='ON' MAKE_TARGET='test sphinx'

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - cmake
      - graphviz 
      - doxygen
      - libboost-all-dev
      - libeigen3-dev
      - libgmp3-dev
      - libmpfr-dev
      - libtbb-dev
      - curl
      - python3
      - python3-pip
  homebrew:
    packages:
      - cmake
      - graphviz 
      - doxygen
      - boost
      - eigen
      - gmp
      - mpfr
      - tbb
      - curl
      - python3

# When installing through libcgal-dev apt, CMake Error at CGAL Exports.cmake The imported target "CGAL::CGAL Qt5" references the file
install: 
  - curl -LO "https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.13/CGAL-4.13.tar.xz"
  - tar xf CGAL-4.13.tar.xz
  - cd CGAL-4.13
  - cmake -DCMAKE_BUILD_TYPE=Release -DCGAL_HEADER_ONLY=ON .
  - make all
  - sudo make install
  - cd ..
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install --user pytest Cython sphinx sphinxcontrib-bibtex matplotlib numpy scipy

script: 
  - rm -rf build
  - mkdir -p build 
  - cd build 
  - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=${CMAKE_EXAMPLE} -DWITH_GUDHI_TEST=${CMAKE_TEST} -DWITH_GUDHI_UTILITIES=${CMAKE_UTILITIES} -DWITH_GUDHI_PYTHON=${CMAKE_PYTHON} -DUSER_VERSION_DIR=version -DPython_ADDITIONAL_VERSIONS=3 .. 
  - make all ${MAKE_TARGET}
  - cd ..

notifications:
  email:
    on_success: change # default: always
    on_failure: always # default: always
